#include "cbase.h"
#include "icliententitylist.h"
#include "cliententitylist.h"
#include "neo_hud_spectator_overlay.h"

#include "c_neo_player.h"
#include "cdll_client_int.h"
#include "neo_player_shared.h"
#include "neo_scoreboard.h"
#include "neo_weapon_loadout.h"
#include "neo_hud_deathnotice.h"
#include <c_playerresource.h>

#include "iclientmode.h"
#include <vgui/ILocalize.h>
#include <vgui/ISurface.h>
#include <vgui_controls/Controls.h>
#include <vgui_controls/ImageList.h>
#include <vgui/IScheme.h>
#include <vgui_avatarimage.h>

// memdbgon must be the last include file in a .cpp file!!!
#include "tier0/memdbgon.h"

ConVar cl_neo_hud_spectator_overlay_enabled("cl_neo_hud_spectator_overlay_enabled", "0",
		FCVAR_ARCHIVE | FCVAR_DONTRECORD,
		"Whether the spectator overlay HUD is enabled", true, 0.0f, true, 1.0f);

DECLARE_NAMED_HUDELEMENT(CNEOHud_SpectatorOverlay, neo_spectator_overlay);

NEO_HUD_ELEMENT_DECLARE_FREQ_CVAR(SpectatorOverlay, 0.2f);

static const struct Theme
{
	Color hpLossBg = Color(150, 20, 20, 255);
	Color cardBg = Color(20, 20, 20, 180);
	Color deadBg = Color(40, 20, 20, 180);
	Color textPrimary = Color(240, 240, 240, 255);
	Color textSecondary = Color(180, 180, 180, 230);
	Color wepInactive = Color(120, 120, 120, 255);
	Color deadAvatarTint = Color(90, 40, 40, 160);
} OVERLAY_THEME = {};

static constexpr const float FL_CHECK_HP_REDUCTION_DELTA_MAX = 1.5f;

CNEOHud_SpectatorOverlay::CNEOHud_SpectatorOverlay(const char* pElementName, vgui::Panel* parent)
	: CHudElement(pElementName), EditablePanel(parent, pElementName)
{
	SetAutoDelete(true);
	m_iHideHudElementNumber = NEO_HUD_ELEMENT_SPECTATOR_OVERLAY;

	if (parent)
	{
		SetParent(parent);
	}
	else
	{
		SetParent(g_pClientMode->GetViewport());
	}

	int iScrWide, iScrTall;
	vgui::surface()->GetScreenSize(iScrWide, iScrTall);
	SetBounds(0, 0, iScrWide, iScrTall);

	SetVisible(true);
}

CNEOHud_SpectatorOverlay::~CNEOHud_SpectatorOverlay()
{
}

static bool ShouldDrawHUD()
{
	return (g_PR && NEORules()
			&& NEORules()->IsTeamplay()
			&& GetLocalPlayerTeam() == TEAM_SPECTATOR
			&& cl_neo_hud_spectator_overlay_enabled.GetBool());
}

void CNEOHud_SpectatorOverlay::Paint()
{
	if (!ShouldDrawHUD())
	{
		return;
	}
	PaintNeoElement();
	BaseClass::Paint();
}

void CNEOHud_SpectatorOverlay::ClearAll()
{
	m_iCardsSize = 0;
	V_memset(m_cards, 0, sizeof(m_cards));
	V_memset(m_iTeamPlayersCount, 0, sizeof(m_iTeamPlayersCount));
}

void CNEOHud_SpectatorOverlay::Init()
{
	ListenForGameEvent("round_start");
	ClearAll();
}

void CNEOHud_SpectatorOverlay::LevelShutdown()
{
	ClearAll();
}

void CNEOHud_SpectatorOverlay::FireGameEvent(IGameEvent *event)
{
	const char *type = event->GetName();
	if (0 == V_strcmp(type, "round_start"))
	{
		// Clear animation/fading related variables
		for (int i = 0; i < m_iCardsSize; ++i)
		{
			SpectatorPlayerCard *pCard = &m_cards[i];
			pCard->flLastAttackTime = 0.0f;
			pCard->flLastAliveTime = 0.0f;
			pCard->flLastHPChangeTime = 0.0f;
			pCard->iLastHP = 0;
		}
	}
}

void CNEOHud_SpectatorOverlay::ApplySchemeSettings(vgui::IScheme* pScheme)
{
	BaseClass::ApplySchemeSettings(pScheme);

	LoadControlSettings("scripts/HudLayout.res");

	int iScrWide, iScrTall;
	vgui::surface()->GetScreenSize(iScrWide, iScrTall);
	SetBounds(0, 0, iScrWide, iScrTall);

	SetFgColor(COLOR_TRANSPARENT);
	SetBgColor(COLOR_TRANSPARENT);
}

void CNEOHud_SpectatorOverlay::UpdateStateForNeoHudElementDraw()
{
	bool bScoreboardNeedUpdate = false;

	const int iOldCardsSize = m_iCardsSize;
	SpectatorPlayerCard oldCards[MAX_PLAYERS_ARRAY_SAFE] = {};
	static_assert(sizeof(oldCards) == sizeof(m_cards));
	V_memcpy(oldCards, m_cards, sizeof(oldCards));

	m_iCardsSize = 0;
	V_memset(m_iTeamPlayersCount, 0, sizeof(m_iTeamPlayersCount));
	V_memset(m_cards, 0, sizeof(m_cards));

	const auto *pLocalPlayer = C_NEO_Player::GetLocalNEOPlayer();
	if (!pLocalPlayer || !ShouldDrawHUD())
	{
		return;
	}

	for (int i = 1; i <= gpGlobals->maxClients; ++i)
	{
		if (i == pLocalPlayer->entindex() || !g_PR->IsValid(i) || g_PR->IsHLTV(i))
		{
			continue;
		}

		const int iTeam = g_PR->GetTeam(i);
		if (false == IN_BETWEEN_EQ(FIRST_GAME_TEAM, iTeam, TEAM__TOTAL - 1)
				|| (m_iCardsSize >= MAX_PLAYERS_ARRAY_SAFE))
		{
			continue;
		}

		SpectatorPlayerCard *pCard = &m_cards[m_iCardsSize++];
		++m_iTeamPlayersCount[iTeam];

		// Reuse the avatar image already generated by the scoreboard
		pCard->pAvatarAlive = nullptr;
		pCard->pAvatarDead = nullptr;
		if (g_pNeoScoreBoard && g_pNeoScoreBoard->m_pImageList && CNEOScoreBoard::ShowAvatars())
		{
			const CSteamID steamId = GetSteamIDForPlayerIndex(i);
			if (steamId.IsValid())
			{
				CUtlMap<CSteamID, MapAvatarValue> &mapAvatars = g_pNeoScoreBoard->m_mapAvatarsToImageList;
				const int iMapIdx = mapAvatars.Find(steamId);
				bool bAvatarNeedUpdate = true;
				if (iMapIdx != mapAvatars.InvalidIndex())
				{
					const MapAvatarValue &avatar = mapAvatars[iMapIdx];
					if (avatar.i184Idx >= 0)
					{
						pCard->pAvatarAlive = static_cast<CAvatarImage *>(g_pNeoScoreBoard->m_pImageList->GetImage(avatar.i184Idx));
						bAvatarNeedUpdate = false;
					}
					if ((!pCard->pAvatarAlive || !pCard->pAvatarAlive->IsValid()) && avatar.i64Idx >= 0)
					{
						pCard->pAvatarAlive = static_cast<CAvatarImage *>(g_pNeoScoreBoard->m_pImageList->GetImage(avatar.i64Idx));
					}
					if ((!pCard->pAvatarAlive || !pCard->pAvatarAlive->IsValid()) && avatar.i32Idx >= 0)
					{
						pCard->pAvatarAlive = static_cast<CAvatarImage *>(g_pNeoScoreBoard->m_pImageList->GetImage(avatar.i32Idx));
					}

					if (avatar.i184DeadIdx >= 0)
					{
						pCard->pAvatarDead = static_cast<CAvatarImage *>(g_pNeoScoreBoard->m_pImageList->GetImage(avatar.i184DeadIdx));
						bAvatarNeedUpdate = false;
					}
					if ((!pCard->pAvatarAlive || !pCard->pAvatarAlive->IsValid()) && avatar.i64DeadIdx >= 0)
					{
						pCard->pAvatarDead = static_cast<CAvatarImage *>(g_pNeoScoreBoard->m_pImageList->GetImage(avatar.i64DeadIdx));
					}
					if ((!pCard->pAvatarAlive || !pCard->pAvatarAlive->IsValid()) && avatar.i32DeadIdx >= 0)
					{
						pCard->pAvatarDead = static_cast<CAvatarImage *>(g_pNeoScoreBoard->m_pImageList->GetImage(avatar.i32DeadIdx));
					}
				}
				bScoreboardNeedUpdate = bScoreboardNeedUpdate || bAvatarNeedUpdate;
			}
		}

		Q_UTF8ToUnicode(g_PR->GetPlayerName(i), pCard->wszPlayerName, sizeof(pCard->wszPlayerName));

		C_NEO_Player *pNeoPlayer = ToNEOPlayer(UTIL_PlayerByIndex(i));

		// XP and class from player resource
		pCard->iTeam = iTeam;
		pCard->iXP = g_PR->GetXP(i);
		pCard->iDeath = g_PR->GetDeaths(i);
		pCard->iClass = g_PR->GetClass(i);

		pCard->iRoundKills = 0;
		if (pNeoPlayer)
		{
			pCard->iUserID = pNeoPlayer->GetUserID();
			pCard->iEntIndex = pNeoPlayer->entindex();

			for (int j = 0; j < gRoundKillerUserIDsSize; ++j)
			{
				pCard->iRoundKills += (gRoundKillerUserIDs[j] == pCard->iUserID);
			}
		}

		// Health - NEO NOTE (nullsystem): GetHealth can be non-0 even when dead
		pCard->bAlive = g_PR->IsAlive(i);
		pCard->iHP = pCard->bAlive ? g_PR->GetHealth(i) : 0;

		// Deal with timings to can do animations/fading
		SpectatorPlayerCard *pOldCard = nullptr;
		if (pCard->iUserID > 0)
		{
			if (oldCards[m_iCardsSize - 1].iUserID == pCard->iUserID)
			{
				pOldCard = &oldCards[m_iCardsSize - 1];
			}
			else
			{
				for (int j = 0; j < iOldCardsSize; ++j)
				{
					if (oldCards[j].iUserID == pCard->iUserID)
					{
						pOldCard = &oldCards[j];
						break;
					}
				}
			}
		}
		if (pOldCard)
		{
			// Alive -> dead
			pCard->flLastAliveTime = pOldCard->flLastAliveTime;
			if (pOldCard->bAlive && !pCard->bAlive)
			{
				pCard->flLastAliveTime = gpGlobals->curtime;
			}

			// HP reduction
			pCard->flLastHPChangeTime = pOldCard->flLastHPChangeTime;
			pCard->iLastHP = pOldCard->iLastHP;
			if ((pOldCard->iHP > pCard->iHP)
					&& ((gpGlobals->curtime - pCard->flLastHPChangeTime) > FL_CHECK_HP_REDUCTION_DELTA_MAX))
			{
				pCard->flLastHPChangeTime = gpGlobals->curtime;
				pCard->iLastHP = pOldCard->iHP;
			}
		}

		// Weapon
		pCard->flLastAttackTime = 0.0f;
		pCard->iTotalWeaponIcons = 0;
		pCard->iWeaponIdxPrimary = -1;
		pCard->iWeaponIdxActive = -1;
		if (pNeoPlayer)
		{
			const auto *pWepActive = static_cast<CNEOBaseCombatWeapon *>(pNeoPlayer->GetActiveWeapon());
			if (pWepActive)
			{
				pCard->flLastAttackTime = pWepActive->GetLastAttackTime();
			}

			wchar_t wszWeaponIcon[2] = {};
			for (int j = 0; j < MAX_WEAPONS; ++j)
			{
				// NEO NOTE (nullsystem): Disallow knife, but keep ghost in
				// array but ghost only for the outside indicator will be
				// skipped over in the weapon icons list
				if (const auto *pNeoWep = static_cast<CNEOBaseCombatWeapon *>(pNeoPlayer->GetWeapon(j));
						pNeoWep && pNeoWep->WeaponIndex() != NEO_WIDX_KNIFE)
				{
					if (pNeoWep->GetSlot() == 0)
					{
						pCard->iWeaponIdxPrimary = pCard->iTotalWeaponIcons;
					}
					if (pWepActive == pNeoWep)
					{
						pCard->iWeaponIdxActive = pCard->iTotalWeaponIcons;
					}

					// Icons are really only 1 character long
					Q_UTF8ToUnicode(pNeoWep->GetDeathIcon(),
							wszWeaponIcon, sizeof(wszWeaponIcon));
					pCard->wcaWeaponIcons[pCard->iTotalWeaponIcons++] = wszWeaponIcon[0];
				}
			}
		}
	}

	// NEO NOTE (nullsystem): This is so the spectator don't need to tab press
	// on the scoreboard to update the avatar. Generally only happens in the
	// beginning of match/demo
	//
	// NEO TODO (nullsystem): Move avatar handling off to something separate from
	// the scoreboard but shared between scoreboard, overlay, and killer info
	if (bScoreboardNeedUpdate)
	{
		g_pNeoScoreBoard->Update();
	}
}

void CNEOHud_SpectatorOverlay::DrawPlayerCard(const SpectatorPlayerCard &card,
		const bool bIsLeftSide,
		const int x, const int y,
		const int wide, const int tall,
		const Color accentColor, const float flWideAs43) const
{
	// Card background
	static constexpr const float FL_LAST_ALIVE_DELTA_MAX = 1.5f;
	const float flLastAliveDelta = gpGlobals->curtime - card.flLastAliveTime;
	if (card.bAlive || flLastAliveDelta > FL_LAST_ALIVE_DELTA_MAX || flLastAliveDelta < 0.0f)
	{
		vgui::surface()->DrawSetColor(card.bAlive ? OVERLAY_THEME.cardBg : OVERLAY_THEME.deadBg);
	}
	else
	{
		// Just died fade from brighter red to normal dead red background
		Color deadFadeBg = OVERLAY_THEME.deadBg;
		deadFadeBg[0] += 80.0f * ((FL_LAST_ALIVE_DELTA_MAX - flLastAliveDelta) * (1.0f / FL_LAST_ALIVE_DELTA_MAX));
		vgui::surface()->DrawSetColor(deadFadeBg);
	}
	vgui::surface()->DrawFilledRect(x, y, x + wide, y + tall);

	const int iAvatarSize = tall;
	const int iAvatarX = bIsLeftSide ? x : x + wide - iAvatarSize;
	const int iAvatarY = y;

	// Draw avatar background
	vgui::surface()->DrawSetColor(OVERLAY_THEME.cardBg);
	vgui::surface()->DrawOutlinedRect(iAvatarX, iAvatarY, iAvatarX + iAvatarSize, iAvatarY + iAvatarSize);
	vgui::surface()->DrawFilledRect(iAvatarX + 1, iAvatarY + 1, iAvatarX + iAvatarSize - 1, iAvatarY + iAvatarSize - 1);

	// Draw the actual Steam avatar (borrowed from the scoreboard's avatar list)
	CAvatarImage *pAvatar = card.bAlive ? card.pAvatarAlive : card.pAvatarDead;
	if (pAvatar && pAvatar->IsValid())
	{
		pAvatar->SetPos(iAvatarX, iAvatarY);
		pAvatar->SetSize(iAvatarSize, iAvatarSize);
		pAvatar->Paint();
	}
	else if (card.wszPlayerName[0])
	{
		// Fallback when no avatar: first character of the player name
		// Usually just bots though
		wchar_t wszInitial[2] = { card.wszPlayerName[0], L'\0' };
		vgui::surface()->DrawSetTextColor(OVERLAY_THEME.textSecondary);
		vgui::surface()->DrawSetTextFont(m_hInfoFont);
		int iInitialWide = 0;
		[[maybe_unused]] int iInitialTall = 0;
		vgui::surface()->GetTextSize(m_hInfoFont, wszInitial, iInitialWide, iInitialTall);
		vgui::surface()->DrawSetTextPos(iAvatarX + (iAvatarSize - iInitialWide) / 2, iAvatarY + (iAvatarSize - vgui::surface()->GetFontTall(m_hInfoFont)) / 2);
		vgui::surface()->DrawPrintText(wszInitial, 1);
	}

	const int iTextPad = flWideAs43 / 360.0f;

	// HP text or dead icon over avatar
	if (card.bAlive)
	{
		wchar_t wszHP[16] = {};
		V_swprintf_safe(wszHP, L"%d", card.iHP);

		int iWideHP = 0, iTallHP = 0;
		vgui::surface()->GetTextSize(m_hRKHPFont, wszHP, iWideHP, iTallHP);

		const int iHPTextX = bIsLeftSide
				? iAvatarX + iTextPad
				: iAvatarX + iAvatarSize - iWideHP - iTextPad;
		const int iHPTextY = iAvatarY + iAvatarSize - iTallHP;

		// Back
		vgui::surface()->DrawSetTextFont(m_hRKHPBackFont);
		vgui::surface()->DrawSetTextColor(COLOR_BLACK);
		vgui::surface()->DrawSetTextPos(iHPTextX, iHPTextY);
		vgui::surface()->DrawPrintText(wszHP, V_wcslen(wszHP));

		// Front
		vgui::surface()->DrawSetTextFont(m_hRKHPFont);
		vgui::surface()->DrawSetTextColor(OVERLAY_THEME.textPrimary);
		vgui::surface()->DrawSetTextPos(iHPTextX, iHPTextY);
		vgui::surface()->DrawPrintText(wszHP, V_wcslen(wszHP));
	}
	else
	{
		// Dead icon
		vgui::surface()->DrawSetColor(COLOR_WHITE);
		vgui::surface()->DrawSetTexture(m_iDeadTexture);
		vgui::surface()->DrawTexturedRect(
				iAvatarX,
				iAvatarY,
				iAvatarX + iAvatarSize,
				iAvatarY + iAvatarSize);
	}

	// Round kills, over avatar, upper section
	if (card.iRoundKills > 0)
	{
		// Kills in current round
		wchar_t wszNum[8] = {};
		V_swprintf_safe(wszNum, L"x%d", card.iRoundKills);

		int iWideRK = 0, iTallRK = 0;
		vgui::surface()->GetTextSize(m_hRKHPFont, wszNum, iWideRK, iTallRK);

		const int iRKTextX = bIsLeftSide
				? iAvatarX + iTextPad
				: iAvatarX + iAvatarSize - iWideRK - iTextPad;
		const int iRKTextY = iAvatarY;

		// Back
		vgui::surface()->DrawSetTextFont(m_hRKHPBackFont);
		vgui::surface()->DrawSetTextColor(COLOR_BLACK);
		vgui::surface()->DrawSetTextPos(iRKTextX, iRKTextY);
		vgui::surface()->DrawPrintText(wszNum, V_wcslen(wszNum));

		// Front
		vgui::surface()->DrawSetTextFont(m_hRKHPFont);
		vgui::surface()->DrawSetTextColor(OVERLAY_THEME.textPrimary);
		vgui::surface()->DrawSetTextPos(iRKTextX, iRKTextY);
		vgui::surface()->DrawPrintText(wszNum, V_wcslen(wszNum));
	}

	// HP bar(s)
	{
		const int hpX = bIsLeftSide ? x + iAvatarSize : x;
		const int hpY = y;
		const int hpW = wide - iAvatarSize;
		const int hpH = static_cast<int>(iAvatarSize / 2.0f);
		const float flClassHP = static_cast<float>(IN_BETWEEN_AR(0, card.iClass, NEO_CLASS__ENUM_COUNT)
			? MAX_HEALTH_FOR_CLASS[card.iClass] : 100);

		const float flHpPerc = clamp(card.iHP / flClassHP, 0.0f, 1.0f);
		const int iFillHPWide = static_cast<int>(hpW * flHpPerc);

		// Red HP reduction/loss bar
		const float flLastHPChangeDelta = gpGlobals->curtime - card.flLastHPChangeTime;
		if (card.iLastHP > card.iHP
				&& IN_BETWEEN_EQ(0.0f, flLastHPChangeDelta, FL_CHECK_HP_REDUCTION_DELTA_MAX))
		{
			static constexpr const float FL_CHECK_HP_REDUCTION_DELTA_ANIM_START =
					FL_CHECK_HP_REDUCTION_DELTA_MAX * 0.40f;
			static constexpr const float FL_CHECK_HP_REDUCTION_ANIM_MAX =
					FL_CHECK_HP_REDUCTION_DELTA_MAX - FL_CHECK_HP_REDUCTION_DELTA_ANIM_START;

			const float flLastHpPerc = clamp(card.iLastHP / flClassHP, 0.0f, 1.0f);
			int iFillReductHP = static_cast<int>(hpW * flLastHpPerc) - iFillHPWide;
			if (iFillReductHP > 0)
			{
				if (flLastHPChangeDelta > FL_CHECK_HP_REDUCTION_DELTA_ANIM_START)
				{
					iFillReductHP = static_cast<float>(iFillReductHP)
							* static_cast<float>(
									(FL_CHECK_HP_REDUCTION_ANIM_MAX - (flLastHPChangeDelta - FL_CHECK_HP_REDUCTION_DELTA_ANIM_START))
									* (1.0f / FL_CHECK_HP_REDUCTION_ANIM_MAX));
				}
				const int iHPXStart = bIsLeftSide
						? hpX + iFillHPWide
						: hpX + hpW - iFillHPWide - iFillReductHP;

				vgui::surface()->DrawSetColor(OVERLAY_THEME.hpLossBg);
				vgui::surface()->DrawFilledRect(
						iHPXStart,
						hpY,
						iHPXStart + iFillReductHP,
						hpY + hpH);
			}
		}

		// HP bar
		if (card.iHP > 0)
		{
			Color colorHpBar = accentColor;
			colorHpBar[0] *= 0.8f;
			colorHpBar[1] *= 0.8f;
			colorHpBar[2] *= 0.8f;

			static constexpr const int FADE_RANGE = 196;
			static constexpr const int FADE_START = 255 - FADE_RANGE;
			const int iMaxFade = Clamp(static_cast<int>(flHpPerc * static_cast<float>(FADE_RANGE)), 0, FADE_RANGE);
			const int iHPXStart = bIsLeftSide ? hpX : hpX + (hpW - iFillHPWide);
			vgui::surface()->DrawSetColor(colorHpBar);
			vgui::surface()->DrawFilledRectFade(
					iHPXStart,
					hpY,
					iHPXStart + iFillHPWide,
					hpY + hpH,
					bIsLeftSide ? FADE_START : FADE_START + iMaxFade,
					bIsLeftSide ? FADE_START + iMaxFade : FADE_START,
					true);
		}
	}

	// Player name | Class
	{
		vgui::surface()->DrawSetTextFont(m_hNameFont);

		// Right-side right-aligned player name
		int iPlayerNameWide = 0, iPlayerNameTall = 0;
		vgui::surface()->GetTextSize(m_hNameFont, card.wszPlayerName, iPlayerNameWide, iPlayerNameTall);

		const int iNameX = bIsLeftSide
				? x + iAvatarSize + iTextPad
				: x + (wide - iAvatarSize) - iTextPad - iPlayerNameWide;
		const int iNameY = y + (((iAvatarSize / 2.0f) - iPlayerNameTall) / 2.0f);

		vgui::surface()->DrawSetTextColor(card.bAlive
				? OVERLAY_THEME.textPrimary
				: Color(140, 140, 150, 200));
		vgui::surface()->DrawSetTextPos(iNameX, iNameY);
		vgui::surface()->DrawPrintText(card.wszPlayerName, V_wcslen(card.wszPlayerName));

		// Class name
		vgui::surface()->DrawSetTextFont(m_hClassFont);
		const wchar_t *pwszClassName = GetNeoClassNameW(card.iClass);
		int iClassNameWide = 0, iClassNameTall = 0;
		vgui::surface()->GetTextSize(m_hClassFont, pwszClassName, iClassNameWide, iClassNameTall);
		const int iClNamePosX = bIsLeftSide
				? x + iAvatarSize + (wide - iAvatarSize) - iTextPad - iClassNameWide
				: x + iTextPad;
		const int iClNamePosY = y + (((iAvatarSize / 2.0f) - iClassNameTall) / 2.0f);

		vgui::surface()->DrawSetTextColor(card.bAlive
				? OVERLAY_THEME.textPrimary
				: Color(140, 140, 150, 200));
		vgui::surface()->DrawSetTextPos(iClNamePosX, iClNamePosY);
		vgui::surface()->DrawPrintText(pwszClassName, V_wcslen(pwszClassName));
	}

	// Extra info row: XP | Death | Round kills | Weapon logo
	{
		const int iInfoTall = iAvatarSize / 2.0f;
		const int iInfoY = y + iInfoTall;
		const int iTotalW = wide - iAvatarSize - (iTextPad * 2);

		// Sizing split between XP and death
		const int iGap = flWideAs43 / 360.0f;
		const int iColW = iTotalW / 5;

		const int iTextFontTall = vgui::surface()->GetFontTall(m_hInfoFont);
		const int iTextFontOffset = (iInfoTall - iTextFontTall) / 2.0f;

		int iRankIconWide = 0, iRankIconTall = 0;
		{
			const wchar_t wszRankIcon[] = { NEO_HUD_DEATHNOTICEICON_LT, L'\0' };
			vgui::surface()->GetTextSize(g_hFontKillfeedIcons, wszRankIcon, iRankIconWide, iRankIconTall);
		}

		int iDeathIconWide = 0, iDeathIconTall = 0;
		{
			const wchar_t wszDeathsIcon[] = { NEO_HUD_DEATHNOTICEICON_KILL, L'\0' };
			vgui::surface()->GetTextSize(g_hFontKillfeedIcons, wszDeathsIcon, iDeathIconWide, iDeathIconTall);
		}

		wchar_t wszNum[8] = {};
		const int iInfoX = bIsLeftSide ? x + iAvatarSize + iTextPad : x + (wide - iAvatarSize) - iTextPad;

		// XP (left of death)
		const int iXPosXP = bIsLeftSide ? iInfoX + iGap : iInfoX - (iColW * 2) + iGap;
		// XP - Rank Icon
		{
			const wchar_t wcRankIcon = NEO_HUD_DEATHNOTICEICON_RANKLESS_DOG + GetRank(card.iXP);
			vgui::surface()->DrawSetTextFont(g_hFontKillfeedIcons);
			vgui::surface()->DrawSetTextPos(iXPosXP + iTextPad, iInfoY + ((iInfoTall - iRankIconTall) / 2.0f));
			vgui::surface()->DrawPrintText(&wcRankIcon, 1);
		}
		// XP - Number
		{
			V_swprintf_safe(wszNum, L"%d", card.iXP);
			vgui::surface()->DrawSetTextFont(m_hInfoFont);
			vgui::surface()->DrawSetTextPos(iXPosXP + iTextPad + iRankIconWide + iTextPad, iInfoY + iTextFontOffset);
			vgui::surface()->DrawPrintText(wszNum, V_wcslen(wszNum));
		}

		// Death (right of XP)
		const int iXPosDeath = bIsLeftSide ? iInfoX + iColW + iGap : iInfoX - iColW + iGap;
		// Death - Icon
		{
			static const wchar_t WC_KILLICON = NEO_HUD_DEATHNOTICEICON_KILL;
			vgui::surface()->DrawSetTextFont(g_hFontKillfeedIcons);
			vgui::surface()->DrawSetTextPos(iXPosDeath, iInfoY + ((iInfoTall - iDeathIconTall) / 2.0f));
			vgui::surface()->DrawPrintText(&WC_KILLICON, 1);
		}
		// Death - Number
		{
			V_swprintf_safe(wszNum, L"%d", card.iDeath);
			vgui::surface()->DrawSetTextFont(m_hInfoFont);
			vgui::surface()->DrawSetTextPos(iXPosDeath + iDeathIconWide + iTextPad, iInfoY + iTextFontOffset);
			vgui::surface()->DrawPrintText(wszNum, V_wcslen(wszNum));
		}

		if (card.bAlive)
		{
			int iWepPosOffsetX = iTextPad;

			// Primary (larger icon, most right in card for Jinrai, most left in card for NSF)
			// If ghost is primary, this is differed to the ghoster player indicator
			if (card.iWeaponIdxPrimary >= 0
					&& NEO_HUD_DEATHNOTICEICON_GHOST != card.wcaWeaponIcons[card.iWeaponIdxPrimary])
			{
				wchar_t wszWeaponIcon[2] = { card.wcaWeaponIcons[card.iWeaponIdxPrimary], L'\0' };

				int iWepWide = 0, iWepTall = 0;
				vgui::surface()->GetTextSize(g_hFontKillfeedIcons, wszWeaponIcon, iWepWide, iWepTall);

				const int iXPosWepIcon = bIsLeftSide ? x + wide - iTextPad - iWepWide : x + iTextPad;
				iWepPosOffsetX += iWepWide + iTextPad;
				vgui::surface()->DrawSetTextColor((card.iWeaponIdxPrimary == card.iWeaponIdxActive)
						? OVERLAY_THEME.textPrimary : OVERLAY_THEME.wepInactive);
				vgui::surface()->DrawSetTextFont(g_hFontKillfeedIcons);
				vgui::surface()->DrawSetTextPos(iXPosWepIcon, iInfoY + ((iInfoTall - iWepTall) / 2.0f));
				vgui::surface()->DrawPrintText(wszWeaponIcon, 1);
			}

			// Secondary + Throwables (smaller icons)
			for (int i = 0; i < card.iTotalWeaponIcons; ++i)
			{
				if (i == card.iWeaponIdxPrimary)
				{
					continue;
				}

				wchar_t wszWeaponIcon[2] = { card.wcaWeaponIcons[i], L'\0' };

				int iWepWide = 0, iWepTall = 0;
				vgui::surface()->GetTextSize(m_hSmallWeaponsFont, wszWeaponIcon, iWepWide, iWepTall);

				const int iXPosWepIcon = bIsLeftSide ? x + wide - iWepPosOffsetX - iWepWide : x + iWepPosOffsetX;
				iWepPosOffsetX += iWepWide + iTextPad;
				vgui::surface()->DrawSetTextColor((i == card.iWeaponIdxActive)
						? OVERLAY_THEME.textPrimary : OVERLAY_THEME.wepInactive);
				vgui::surface()->DrawSetTextFont(m_hSmallWeaponsFont);
				vgui::surface()->DrawSetTextPos(iXPosWepIcon, iInfoY + ((iInfoTall - iWepTall) * 0.66f));
				vgui::surface()->DrawPrintText(wszWeaponIcon, 1);
			}
		}
	}

	// Ghoster player indicator - Jinrai right side, NSF left side
	if (card.iEntIndex == NEORules()->GetGhosterPlayer())
	{
		const wchar_t WSZ_DNI_GHOST[] = { NEO_HUD_DEATHNOTICEICON_GHOST, L'\0' };

		int iGhostWide = 0, iGhostTall = 0;
		vgui::surface()->GetTextSize(m_hGhostFont, WSZ_DNI_GHOST, iGhostWide, iGhostTall);

		vgui::surface()->DrawSetTextColor(
				(card.iWeaponIdxActive >= 0
				 		&& NEO_HUD_DEATHNOTICEICON_GHOST == card.wcaWeaponIcons[card.iWeaponIdxActive])
					? OVERLAY_THEME.textPrimary
					: OVERLAY_THEME.wepInactive);
		vgui::surface()->DrawSetTextFont(m_hGhostFont);
		if (bIsLeftSide)
		{
			vgui::surface()->DrawSetTextPos(x + wide + iTextPad, y + ((tall - iGhostTall) / 2.0f));
		}
		else
		{
			vgui::surface()->DrawSetTextPos(x - iTextPad - iGhostWide, y + ((tall - iGhostTall) / 2.0f));
		}
		vgui::surface()->DrawPrintText(WSZ_DNI_GHOST, 1);
	}

	// Spectator current observing border
	const auto *pLocalPlayer = C_NEO_Player::GetLocalNEOPlayer();
	if (card.iEntIndex == GetSpectatorTarget()
			&& pLocalPlayer
			&& pLocalPlayer->IsObserver()
			&& (pLocalPlayer->GetObserverMode() == OBS_MODE_IN_EYE
				|| pLocalPlayer->GetObserverMode() == OBS_MODE_CHASE))
	{
		const int iMargin = flWideAs43 / 480.0f;

		vgui::surface()->DrawSetColor(COLOR_WHITE);
		vgui::surface()->DrawFilledRect(x, y - iMargin, x + wide, y);									// top
		vgui::surface()->DrawFilledRect(x, y + tall, x + wide, y + tall + iMargin);						// bottom
		vgui::surface()->DrawFilledRect(x - iMargin, y - iMargin, x, y + tall + iMargin);				// left
		vgui::surface()->DrawFilledRect(x + wide, y - iMargin, x + wide + iMargin, y + tall + iMargin);	// right
	}

	// Weapon firing indicator bar - Jinrai right side, NSF left side 
	static constexpr const float FL_LAST_ATTACK_DELTA_MAX = 0.5f;
	const float flLastAttackDelta = gpGlobals->curtime - card.flLastAttackTime;
	if (IN_BETWEEN_EQ(0.0f, flLastAttackDelta, FL_LAST_ATTACK_DELTA_MAX))
	{
		Color fireIndColor = COLOR_WHITE;
		fireIndColor[3] *= (FL_LAST_ATTACK_DELTA_MAX - flLastAttackDelta) * (1.0f / FL_LAST_ATTACK_DELTA_MAX);
		vgui::surface()->DrawSetColor(fireIndColor);
		if (bIsLeftSide)
		{
			vgui::surface()->DrawFilledRect(x + wide + iTextPad, y, x + wide + (2 * iTextPad), y + tall);
		}
		else
		{
			vgui::surface()->DrawFilledRect(x - (2 * iTextPad), y, x - iTextPad, y + tall);
		}
	}
}

void CNEOHud_SpectatorOverlay::DrawNeoHudElement()
{
	if (!ShouldDrawHUD() || m_iCardsSize <= 0)
	{
		return;
	}

	// In 1920x1080, the player card:
	//   Converted to 4:3 is 1440x1080, calculate from 4:3 width regardless of
	//   16:9/16:10:
	// * Total width (including avatar) of 351px, 1440/4.1=~351
	// * Avatar width of 64px, 1440/22.5=64
	// * Gap from left or right edge of 12px, 1440/120=12
	// * Gap between cards Y-axis of 4px, 1440/360=4
	int iScrWide, iScrTall;
	vgui::surface()->GetScreenSize(iScrWide, iScrTall);

	const float flWide = static_cast<float>(iScrWide);
	float flWideAs43 = static_cast<float>(iScrTall) * (4.0f / 3.0f);
	if (flWideAs43 > flWide) flWideAs43 = flWide;

	const int iTotalCardWide = flWideAs43 / 4.1f;
	const int iAvatarWH = flWideAs43 / 22.5f;
	const int iGapWide = flWideAs43 / 120.0f;
	const int iGapBetween = flWideAs43 / 360.0f;

	// NEO TODO (nullsystem): Draw team's name and logo on top
	for (const auto iTeam : {TEAM_JINRAI, TEAM_NSF})
	{
		const bool bIsLeftSide = (iTeam == TEAM_JINRAI);
		const Color accentColor = g_PR->GetTeamColor(iTeam);

		// Center the column vertically on screen
		const int iTeamCount = m_iTeamPlayersCount[iTeam];
		const int iTotalHeight = (iTeamCount * iAvatarWH) + ((iTeamCount - 1) * iGapBetween);
		const int iColXStart = bIsLeftSide
				? iGapWide
				: static_cast<int>(iScrWide - iTotalCardWide - iGapWide);
		const int iColYStart = ((iScrTall - iTotalHeight) / 2.0f);

		int iPlayerRow = 0;
		for (int i = 0; i < m_iCardsSize; ++i)
		{
			if (m_cards[i].iTeam == iTeam)
			{
				const int iRowY = iColYStart + (iPlayerRow * iAvatarWH)
						+ ((iPlayerRow > 0) ? (iPlayerRow * iGapBetween) : 0);
				DrawPlayerCard(m_cards[i], bIsLeftSide,
						iColXStart, iRowY, iTotalCardWide, iAvatarWH,
						accentColor, flWideAs43);
				++iPlayerRow;
			}
		}
	}
}

