if(NEO_INSTALL_LIBRARIES)
    if(NEO_DEDICATED)
        set(CPACK_PACKAGE_FILE_NAME "neo-${BUILD_DATE_SHORT}-${GIT_HASH}-dedicated-${CMAKE_SYSTEM_NAME}-${CMAKE_BUILD_TYPE}")
    else()
        set(CPACK_PACKAGE_FILE_NAME "neo-${BUILD_DATE_SHORT}-${GIT_HASH}-libraries-${CMAKE_SYSTEM_NAME}-${CMAKE_BUILD_TYPE}")
    endif()
endif()

if(NEO_INSTALL_RESOURCES)
    set(CPACK_PACKAGE_FILE_NAME "neo-${BUILD_DATE_SHORT}-${GIT_HASH}-resources")
endif()

if(OS_WINDOWS)
    set(CPACK_GENERATOR "ZIP")
else()
    set(CPACK_GENERATOR "TXZ")
endif()

set(CPACK_ARCHIVE_THREADS 0)

include(CPack)
