#pragma once

/* NEO NOTE/WARNING (nullsystem):
 * neo_version_info.h is autogenerated by cmake, the actual file to
 * edit is neo_version_info.preproc.h which takes defined cmake variables
 */
static constexpr char BUILD_DATE[] = "@BUILD_DATE@";
static constexpr char BUILD_DATETIME[] = "@BUILD_DATETIME@";
static constexpr char GIT_HASH[] = "@GIT_HASH@";
static constexpr char GIT_LONGHASH[] = "@GIT_LONGHASH@";
static constexpr char OS_BUILD[] = "@OS_BUILD@";
static constexpr char COMPILER_ID[] = "@COMPILER_ID@";
static constexpr char COMPILER_VERSION[] = "@COMPILER_VERSION@";

