#include "cbase.h"
#include "achievements_neo.h"

CAchievementMgr g_AchievementMgrNEO;	// global achievement mgr for NEO

DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_NEO_TUTORIAL_COMPLETE, "NEO_TUTORIAL_COMPLETE", 5 );

DECLARE_NEO_ACHIEVEMENT( ACHIEVEMENT_NEO_TRIAL_50_SECONDS, "NEO_TRIAL_50_SECONDS", 5 );
DECLARE_NEO_ACHIEVEMENT( ACHIEVEMENT_NEO_TRIAL_40_SECONDS, "NEO_TRIAL_40_SECONDS", 5 );
